kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
subjects:
- kind: User
  name: basic@clearify.co
roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io
