kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: selector-env-prod
  annotations:
    anthos.cft.dev/team-namespace-suffix: prod
spec:
  selector:
    matchLabels:
      environment: prod
