kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-prod
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
  - "get"
  - "watch"
  - "list"
