apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: teams.anthos.cft.dev
spec:
  group: anthos.cft.dev
  version: v1alpha1
  scope: Cluster
  names:
    plural: teams
    singular: team
    kind: Team
  validation:
    openAPIV3Schema:
      required:
      - spec
      properties:
        spec:
          # TeamSpec
          type: object
          properties:
            roles:
              type: array
              items:
                type: object
                required:
                - role
                properties:
                  role:
                    type: string
                  users:
                    type: array
                    items:
                      type: string
                  groups:
                    type: array
                    items:
                      type: string
          # /TeamSpec
