kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sre
subjects:
- kind: User
  name: jane@clearify.co
roleRef:
  kind: ClusterRole
  name: sre
  apiGroup: rbac.authorization.k8s.io
